import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";
import "@/app/globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
export const metadata = {
  title: "Timelord.eth",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      <SpeedInsights/>

      </body>
    </html>
  );
}
